engines:
  rubocop:
    enabled: true
  golint:
    enabled: false
  gofmt:
    enabled: true
  eslint:
    enabled: false
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
    languages:
      ruby:
      javascript:


ratings:
   paths:
   - app/**
   - lib/**
   - "**.rb"
   - "**.go"

exclude_paths:
  - spec/**/*
  - vendor/**/*
